# SciKit Learn Preprocessing Overview

In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,100,(10,2))

In [4]:
data

array([[ 8,  3],
       [45, 79],
       [ 4, 72],
       [22, 70],
       [10, 34],
       [31, 76],
       [ 1, 10],
       [31, 80],
       [69, 62],
       [30, 62]])

In [5]:
scaler_model = MinMaxScaler()

In [6]:
scaler_model.fit(data)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [7]:
scaler_model.transform(data)

array([[0.10294118, 0.        ],
       [0.64705882, 0.98701299],
       [0.04411765, 0.8961039 ],
       [0.30882353, 0.87012987],
       [0.13235294, 0.4025974 ],
       [0.44117647, 0.94805195],
       [0.        , 0.09090909],
       [0.44117647, 1.        ],
       [1.        , 0.76623377],
       [0.42647059, 0.76623377]])

In [8]:
# In one step
result = scaler_model.fit_transform(data)

In [9]:
result

array([[0.10294118, 0.        ],
       [0.64705882, 0.98701299],
       [0.04411765, 0.8961039 ],
       [0.30882353, 0.87012987],
       [0.13235294, 0.4025974 ],
       [0.44117647, 0.94805195],
       [0.        , 0.09090909],
       [0.44117647, 1.        ],
       [1.        , 0.76623377],
       [0.42647059, 0.76623377]])

In [10]:
import pandas as pd

In [11]:
data = pd.DataFrame(data=np.random.randint(0,101,(50,4)),columns=['f1','f2','f3','label'])

In [12]:
data.head()

f1  f2  f3  label
0  82  29  81     26
1  78  81  78     91
2  35  43  80     46
3  28  10  45     70
4  80   3  66     62

In [13]:
x = data[['f1','f2','f3']] # Alternatively x = data.drop('label',axis=1)
y = data['label']

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=101)

In [16]:
X_train.shape

(35, 3)

In [17]:
X_test.shape

(15, 3)

In [18]:
y_train.shape

(35,)

In [19]:
y_test.shape

(15,)

# Cheers!